### ISSUE TITLE
These relative modules were not found:

### ISSUE THREAD

**Issue by jamdodot** [eddievandeer/vue3-chatroom#1]
![Snipaste_2021-10-15_19-20-41](https://user-images.githubusercontent.com/33199864/137479322-515a005c-309c-47d5-8f25-3077a6b4612f.png)
这些文件没找到啊 是不是没提交上来啊

**Comment by eddievandeer** [comment]
> ![Snipaste_2021-10-15_19-20-41](https://user-images.githubusercontent.com/33199864/137479322-515a005c-309c-47d5-8f25-3077a6b4612f.png) 这些文件没找到啊 是不是没提交上来啊

是的，预计明天上传~~

**Comment by eddievandeer** [comment]
> > ![Snipaste_2021-10-15_19-20-41](https://user-images.githubusercontent.com/33199864/137479322-515a005c-309c-47d5-8f25-3077a6b4612f.png) 这些文件没找到啊 是不是没提交上来啊
> 
> 是的，预计明天上传~~

已上传该项目的全部文件~~
如果喜欢的话希望点一个免费的star支持一下，谢谢！
